### ISSUE TITLE
NameError: name '_replaceByList' is not defined

### ISSUE THREAD

**Issue by MuhammadSabah** [AsoSoft/AsoSoft-Library-py#4]
When trying to use **Normalize** method, this error happens:

`print(asosoft.Normalize("دەقی"))`

```
Traceback (most recent call last):
  File "/Users/muhammadsabah1/PycharmProjects/filter-text/main.py", line 8, in <module>
    print(asosoft.Normalize("دەقی«کوردی » و ڕێنووس ،((خاڵبەندی )) چۆنە ؟"))
  File "/Users/muhammadsabah1/PycharmProjects/filter-text/.venv/lib/python3.9/site-packages/asosoft/Normalize.py", line 209, in Normalize
    text = _replaceByList(text, normalization_replaces["NormalizeKurdish1"])
NameError: name '_replaceByList' is not defined
```

**Comment by aso-mehmudi** [comment]
fixed
